document.getElementById("header").innerHTML = '<div class="bloc none full-width-bloc l-bloc " id="bloc-0">'
  + '<div class="container bloc-lg bloc-sm-lg">'
  + '<div class="row">'
  + '<div class="col-12 col-md-2 col-lg-2 heading">'
  + '<img id="csirlogo" style="height: 110px; "'
  + 'src="../img/CSIR-Logo-With-Tagline-Seleceted-Bilingual-01.png" class="img-fluid float-lg-none"'
  + 'alt="CSIR Logo-With-Tagline-Seleceted-Bilingual-01" />'
  + '</div>'
  + '<div class="col-12 offset-lg--1 col-lg-8 col-md-8 heading" id="heading">'
  + '<h5 class="text-lg-center tc-black text-md-center">'
  + 'वैज्ञानिक तथा औद्योगिक अनुसंधान परिषद्</h5>'
  + '<h5 class="text-lg-center tc-black text-md-center">'
  + 'Council of Scientific and Industrial Research</h5>'
  + '<h5 class="text-lg-center tc-black text-md-center" id="heading2">'
  + 'विज्ञान और प्रौद्योगिकी मंत्रालय</h5>'
  + '<h5 class="text-lg-center tc-black text-md-center" id="heading2">'
  + 'Ministry of Science and Technology, Govt. of India</h5>'
  + '</div>'
  + '<div class="col-12 col-lg-2 col-md-2 heading">'
  + '<a target="_blank"><img src="../img/G20%20theme%20and%20logo.png" class="img-style float-lg-right"'
  + 'alt="G20%20theme%20and%20logo" /></a>'
  +'</div></div></div></div>';
